sudo: required
services:
  - docker

before_install:
  - docker build -t yassirkens/react-test -f ./client/Dockerfile.dev ./clients

script:
  - docker run -e CI=true yassirkens/react-test npm test

after_success:
  - docker build -t yassirkens/multi-client ./client
  - docker build -t yassirkens/multi-nginx ./nginx
  - docker build -t yassirkens/multi-server ./server
  - docker build -t yassirkens/multi-worker ./worker